### ISSUE TITLE
Plugin functionality overview

### ISSUE THREAD

**Issue by edvin** [edvin/fxlauncher-gradle-plugin#1]
# Goals

The plugin must perform the following high level operations:
### Copy dependencies
- Bundle application jar and dependencies to staging directory
  - Copy all resolved artifacts to a staging directory
### Create `app.xml` manifest
- Generate `app.xml` from plugin properties and embed it inside fxlauncher.jar in the staging directory
  - Manifest is created by calling `fxlauncher.CreateManifest.create(URI baseURI, String launchClass, Path stagingPath)` (in-process if possible)
### Deploy
- Deploy the artifacts via scp or sftp
  - Possibly use [jsch](http://www.jcraft.com/jsch/) to perform the upload of all files in staging folder to configured destination (host, user, password, target-folder) or simply call out to scp
### Create Native Installer
- Generate native installer
  - Call `javapackager` binary from the JDK
  - Parameters can be seen in the [gradle demo project](https://github.com/edvin/fxldemo-gradle/blob/master/build.gradle#L74)

**Comment by edvin** [comment]
@aalmiray I've tried to describe the processes above - is this enough to get started? What I need help with the most is probably setting up the project and the code to resolve artifacts needed for the `Copy dependencies` step. `jsch` integration and calling `javapackager` is probably straight forward once the goals are configured :)

If you have the chance to help me get started here I'll be forever grateful :)

**Comment by aalmiray** [comment]
Of course. Give me a couple of days and I'll push a PR with the base code 😄

**Comment by edvin** [comment]
Thank you :))
