### ISSUE TITLE
Gradle plugin repository is behind

### ISSUE THREAD

**Issue by jpd236** [edvin/fxlauncher-gradle-plugin#16]
https://plugins.gradle.org/plugin/no.tornado.fxlauncher shows 1.0.16 as the latest version

but https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22fxlauncher-gradle-plugin%22 shows a 1.0.18 release.

**Comment by edvin** [comment]
I honestly have no idea how the gradle plugin repository is updated or if I can force an update somehow. Anybody knows?

**Comment by jpd236** [comment]
No personal experience, but this doc might be relevant since it's already on Bintray - https://plugins.gradle.org/docs/reclaiming

**Comment by nhajratw** [comment]
@edvin you updated it to the latest version, so you can close this issue. Thanks!

**Comment by edvin** [comment]
Thanks @nhajratw :)
